### ISSUE TITLE
jsDelivr 加速下载链接

### ISSUE THREAD

**Issue by 88250** [yuanguangxin/421pdf#11]
[八卦汇总.pdf jsDelivr 加速下载](https://cdn.jsdelivr.net/gh/yuanguangxin/421pdf/%E5%85%AB%E5%8D%A6%E6%B1%87%E6%80%BB.pdf)

参考 [GitHub 图床的正确用法，通过 jsDelivr CDN 全球加速](https://hacpai.com/article/1583894928771)

**Comment by yuanguangxin** [comment]
👌
