### ISSUE TITLE
耻辱！你上了趋势榜你知道吗？丢人！请不要污染github这块净土

### ISSUE THREAD

**Issue by xiuin** [yuanguangxin/421pdf#15]
- 不要把饭圈那一套整到github上来
- 请大家不要只把github当免费网盘、营销机器
- 请保持国人形象

这是一个国际平台，你的一言一行代表的不仅是你自己。当别人在分享机器学习成果、公布新框架、开源各种有用的工具，而你，却在分享八卦汇总，还有不少人在拍手称快，why？

**Comment by yuanguangxin** [comment]
喷了 关你屁事阿 死不死啊喂
